version: "3"
services:
  db:
    image: postgres
    container_name: sql_database
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=travel_lab
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /Users/troyprejusa/Dev/apps/travel-lab/database:/docker-entrypoint-initdb.d
volumes:
  pgdata: