version: "3"
services:
  database:
    image: postgres
    container_name: sql_database
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=travel_lab
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  s3mock:
    image: minio/minio
    container_name: minio_storage
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=ROOTPWD123
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - s3data:/data
    command: server /data --console-address ":9090"

  api_dev:
    image: python:3.10
    container_name: fast_api_dev
    command: /app/src/startup.sh
    volumes:
      - /Users/troyprejusa/Dev/apps/travel-lab/backend:/app
    ports:
      - "8000:8000"   # For the API
      - "5678:5678"   # For VSCode debugger
    depends_on:
      - database
      - s3mock

volumes:
  pgdata:
  s3data: