version: "3"
services:
  api_dev:
    image: python:3.10
    container_name: fast_api_dev
    command: /app/src/startup.sh
    volumes:
      - /Users/troyprejusa/Dev/apps/travel-lab/backend:/app
      - /Users/troyprejusa/Dev/apps/travel-lab/frontend/dist:/app/src/dist
    ports:
      - "8000:8000"   # For the API
      - "5678:5678"   # For VSCode debugger
    depends_on:
      - database_dev

  database_dev:
    image: postgres
    container_name: sql_database
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=travel_lab
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  webserver_dev:
    image: nginx
    container_name: nginx_server
    volumes:
      - /Users/troyprejusa/Dev/apps/travel-lab/nginx.conf:/etc/nginx/nginx.conf:ro
      - /Users/troyprejusa/Dev/dev-certs/travel-lab-certs:/etc/nginx/certs:ro
      - /Users/troyprejusa/Dev/apps/travel-lab/frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "443:443"
    depends_on:
      - api_dev

  # s3mock:
  #   image: minio/minio
  #   container_name: minio_storage
  #   environment:
  #     - MINIO_ROOT_USER=ROOTUSER
  #     - MINIO_ROOT_PASSWORD=ROOTPWD123
  #   ports:
  #     - "9000:9000"
  #     - "9090:9090"
  #   volumes:
  #     - s3data:/data
  #   command: server /data --console-address ":9090"

volumes:
  pgdata:
#   s3data: